[package]
name = "init"
version.workspace = true
edition.workspace = true

[[bin]]
name = "palmeto"
path = "src/main.rs"

[dependencies]
shared  = { path = "../shared" }
pine    = { path = "../pine" }
drivers = { path = "../drivers" }

limine  = { workspace = true }
fdt     = { workspace = true }
spin    = { workspace = true }