[workspace]
members = [
    "pine",
    "drivers",
    "shared",
    "init",
]
exclude = [
    "bindings/flanterm-rs",
    "bindings/limine-rs",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
limine     = { path = "bindings/limine-rs" }
flanterm   = { path = "bindings/flanterm-rs", default-features = false }
bytemuck   = { version = "1.25.2", features = ["derive"]}
spin       = { version = "0.9.9", default-features = false, features = ["once", "mutex", "spin_mutex", "rwlock"] }
bitflags   = "2.13.1"
num-traits = { version = "0.2.19", default-features = false }
fdt        = "0.1.5"

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
strip = "debuginfo"