[package]
name = "pine"
version.workspace = true
edition.workspace = true

[dependencies]
shared   = { path = "../shared" }

limine   = { workspace = true }
flanterm = { workspace = true }
bitflags = { workspace = true }
bytemuck = { workspace = true }
spin     = { workspace = true }
fdt      = { workspace = true }